version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: '${DB_PSSWD}'
      POSTGRES_DB: '${DB_NAME}'
    volumes: 
      - 'database:/var/lib/postgresql/data'
    expose: 
      - 5432
  server:
    build:
      dockerfile: ./tomcat.Dockerfile
      target: dev
    volumes:
      - ./build/libs:/usr/local/tomcat/webapps
    ports:
      - 80:8080
    environment:
      FROM_EMAIL: '${FROM_EMAIL}'
      EMAIL_PASSWORD: '${EMAIL_PASSWORD}'
      DB_PSSWD: '${DB_PSSWD}'
      DB_NAME: '${DB_NAME}'
      DB_HOST: '${DB_HOST}'
      DB_USER: '${DB_USER}'
volumes: 
  database: 

